# Generated by Django 5.1.7 on 2025-03-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_user_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
